# app/core/logging.py

import json
import logging
import sys

from datetime import datetime, timezone

class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:

        # generate the standard message and exception strings
        super().format(record)


        log_payload = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.message, #generated by super().format()
        }

        # attach execption strings if they exist
        if record.exc_text:
            log_payload["exception"] = record.exc_text

        return json.dumps(log_payload)


def setup_logging() -> None:
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(JsonFormatter())

    root_logger = logging.getLogger()
    root_logger.handlers.clear()
    root_logger.addHandler(handler)
    root_logger.setLevel(logging.INFO)